stages:
  - test-lint-build
  - publish
  - release-api

default:
  tags:
    - wopr

test-lint-build-api:
  stage: test-lint-build
  image:
    name: registry.mdcatapult.io/informatics/docker-images/ci/golang
  services:
    - postgres:10.11
  variables:
    POSTGRES_DB: coshh
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  before_script:
    - apt-get update && apt-get install -yq postgresql postgresql-contrib
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f ./scripts/init.sql
  script:
    - go vet ./...
    - go test -v ./... -p 1

  except:
    refs:
      - master
      - tags
    variables:
      - "$CI_COMMIT_MESSAGE =~ /^Setting version to.*/"


publish-api:
  stage: publish
  tags:
    - wopr
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
      - ''
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR/api
      --build-arg VERSION_HASH=$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_SLUG
      --dockerfile $CI_PROJECT_DIR/Dockerfile
  except:
    refs:
      - master
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-api-master:
  stage: publish
  tags:
    - wopr
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
      - ''
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR/api
      --build-arg VERSION_HASH=$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_NAME
      --destination $CI_REGISTRY_IMAGE/api:latest
      --dockerfile $CI_PROJECT_DIR/Dockerfile
  only:
    refs:
      - tags
    variables:
      - "$CI_COMMIT_MESSAGE =~ /^Setting version to.*/"

release-api:
  stage: release-api
  image: registry.mdcatapult.io/informatics/docker-images/ci/golang
  script:
    - release.sh
  only:
    refs:
      - master
  except:
    variables:
      - "$CI_COMMIT_MESSAGE =~ /^Setting version to.*/"