version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      AUTH0_DOMAIN: mdcatapult.eu.auth0.com
      AUTH0_AUDIENCE: https://coshh-api-local.wopr.inf.mdc
      AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
      AUTH0_CLIENT_SECRET: "${AUTH0_CLIENT_SECRET}"
    volumes: 
      - ./assets/labs.csv:/mnt/labs.csv
      - ./assets/projects_041022.csv:/mnt/projects.csv

