version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/init-001.sql:/docker-entrypoint-initdb.d/init-001.sql
      - ./scripts/init-002.sql:/docker-entrypoint-initdb.d/init-002.sql
      - ./scripts/init-003.sql:/docker-entrypoint-initdb.d/init-003.sql

  server:
    build:
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      AUTH0_DOMAIN: mdcatapult.eu.auth0.com
      AUTH0_AUDIENCE: https://coshh-api-local.wopr.inf.mdc
      LABS_CSV: /mnt/${LABS_CSV}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      HOST: db
    volumes:
      - type: volume
        source: vast
        target: ${COSHH_DATA_VOLUME}
        volume:
          nocopy: true


volumes:
  vast:
    driver_opts:
      type: "nfs"
      o: "addr=mdc-vast-nfs.medcat.local,nolock,soft,rw"
      device: ":${COSHH_DATA_SOURCE}"
