version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    volumes: 
      - ./assets/labs.csv:/mnt/labs.csv
      - ./assets/projects_041022.csv:/mnt/projects.csv

