version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      AUTH0_DOMAIN: mdcatapult.eu.auth0.com
      AUTH0_AUDIENCE: https://coshh-api-local.wopr.inf.mdc
      CLIENT_ORIGIN_URL: http://localhost:4020
      PORT: 8080
      LABS_CSV: /mnt/labs.csv
      PROJECTS_CSV: /mnt/projects.csv
    volumes:
      - ./assets/labs.csv:/mnt/labs.csv
      - ./assets/projects_041022.csv:/mnt/projects.csv

