AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Description:
  coshh-app
Parameters:
  Host:
    Type: String
    Description: Database host
    Default: host.docker.internal
  DBUser:
    Type: String
    Description: Database user
    Default: postgres
  DBPassword:
    Type: String
    Description: Database password
    Default: postgres
  Auth0Audience:
    Type: String
    Description: Auth0 audience
    Default: my-auth0-audience
  Auth0Domain:
    Type: String
    Description: Auth0 domain
    Default: my-auth0-domain
Resources:
  Coshh:
    Type: AWS::Serverless::Function
    Properties:
      Handler: coshh
      CodeUri: ./bin/coshh.zip
      Runtime: go1.x
      Timeout: 10
      Environment:
        Variables:
          HOST: !Ref Host
          DBUSER: !Ref DBUser
          PASSWORD: !Ref DBPassword
          AUTH0_AUDIENCE: !Ref Auth0Audience
          AUTH0_DOMAIN: !Ref Auth0Domain
      Events:
        GetChemicals:
          Type: Api
          Properties:
            Path: /chemicals
            Method: get
        PostChemical:
          Type: Api
          Properties:
            Path: /chemical
            Method: post
        PutChemical:
          Type: Api
          Properties:
            Path: /chemical
            Method: put
        MaxChemicalNumber:
          Type: Api
          Properties:
            Path: /chemical/maxchemicalnumber
            Method: get
        GetCupboards:
          Type: Api
          Properties:
            Path: /cupboards
            Method: get
        GetLabs:
          Type: Api
          Properties:
            Path: /labs
            Method: get
        PutChemical:
          Type: Api
          Properties:
            Path: /chemical
            Method: put
        PutHazards:
          Type: Api
          Properties:
            Path: /hazards
            Method: put
        GetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
        TestRoute:
          Type: Api
          Properties:
            Path: /protected
            Method: get
          