AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Description:
  coshh-app
Parameters:
  Host:
    Type: String
    Description: Database host
    Default: host.docker.internal
Resources:
  Coshh:
    Type: AWS::Serverless::Function
    Properties:
      Handler: coshh
      CodeUri: ./bin/coshh.zip
      Runtime: go1.x
      Timeout: 10
      Environment:
        Variables:
          HOST: !Ref Host
      Events:
        GetChemicals:
          Type: Api
          Properties:
            Path: /chemicals
            Method: get
        PostChemical:
          Type: Api
          Properties:
            Path: /chemical
            Method: post
        PutChemical:
          Type: Api
          Properties:
            Path: /chemical
            Method: put
        MaxChemicalNumber:
          Type: Api
          Properties:
            Path: /chemical/maxchemicalnumber
            Method: get
        GetCupboards:
          Type: Api
          Properties:
            Path: /cupboards
            Method: get
        GetLabs:
          Type: Api
          Properties:
            Path: /labs
            Method: get
        PutChemical:
          Type: Api
          Properties:
            Path: /chemical
            Method: put
        PutHazards:
          Type: Api
          Properties:
            Path: /hazards
            Method: put
        GetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get
          